AWSTemplateFormatVersion: "2010-09-09"
Resources:
  S3Role:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: cicd-data-s3
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: S3fullaccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: 'arn:aws:s3:::*'
  S3AccessInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref S3Role

Outputs:
  DPs3rolDetails:
    Description: DP CICD s3 role info
    Value: !Ref S3AccessInstanceProfile
    Export:
      Name: s3role-DPS3RoleProfileName
#        Fn::Sub: "${AWS::StackName}-VPS3RoleProfileName"