---
- name: Provision AWS
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Delete DP stack
      cloudformation:
        stack_name: MyDPStack
        disable_rollback: true
        state: absent
        template: "main.yaml"
        template_parameters:
          KeyName: "us-east-2"